### ISSUE TITLE
No way to give up an item on keyboard

### ISSUE THREAD

**Issue by NexyusNex** [MaierN/isaac-mod-less-talking-more-gaming#1]
Its easy to do it on my controllers of course but when I do it on the keyboard it doesnt work. Maybe its because of keyboard ghosting (you cant press some keys at the same time) or its not added yet. But if you could add a hotkey or something that would be great.

**Comment by MaierN** [comment]
Thanks for reporting the issue. This is probably because of keyboard ghosting, I can't reproduce it with my keyboard.

I just added another way for keyboard users: you can simply press the 'o' key to give the item.

**Comment by NexyusNex** [comment]
Thanks a lot, I'm a little bit late to reply but you were fast. I really like the mod and this is a fix to a lot of my coop issues! Keyboard ghosting is common in cheap keyboards and a lot of people may have the same problem but this update fixed it for me and probably to a lot of other people with ghosting. Thank you once again and great job on the mod!
